#!/bin/bash

echo "🔧 Configuration du STRIPE_WEBHOOK_SECRET dans Supabase"
echo ""
echo "Le secret webhook doit être configuré dans Supabase, pas dans le .env local."
echo ""
echo "Méthode 1 - Via le Dashboard Supabase (RECOMMANDÉ):"
echo "1. Allez sur: https://supabase.com/dashboard/project/yliurdpexhvatzkgehvy/settings/functions"
echo "2. Cliquez sur 'Edge Function Secrets' ou 'Secrets'"
echo "3. Ajoutez un nouveau secret:"
echo "   - Nom: STRIPE_WEBHOOK_SECRET"
echo "   - Valeur: [copiez le secret depuis Stripe dashboard]"
echo "4. Sauvegardez"
echo ""
echo "Méthode 2 - Via Supabase CLI:"
echo "npx supabase secrets set STRIPE_WEBHOOK_SECRET=whsec_VOTRE_SECRET"
echo ""
echo "Où trouver le secret Stripe:"
echo "1. Allez sur: https://dashboard.stripe.com/test/webhooks"
echo "2. Cliquez sur votre webhook"
echo "3. Cliquez 'Reveal' pour voir le secret (commence par whsec_)"
echo "4. Copiez-le et utilisez-le ci-dessus"
echo ""
read -p "Appuyez sur Entrée une fois configuré..."
